version: '3.8'

services:
  web:
    image: jjeongtae/my-web-app:latest
    ports:
      - "80:80"

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: mydb
    volumes:
      - ./db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"

